require:
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'gemfiles/**/*'

Style/StringLiterals:
  Exclude:
    - 'gemfiles/**/*'
