require:
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Gemspec/RequireMFA:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Rails/RakeEnvironment:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Alias:
  EnforcedStyle: prefer_alias

Style/FrozenStringLiteralComment:
  Exclude:
    - 'gemfiles/**/*'

Style/StringLiterals:
  Exclude:
    - 'gemfiles/**/*'
